name: sandbox-autogen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - playwright
  - pip
  - pip:
    - python-dotenv
    - autogen-agentchat
    - autogen-ext[openai,web-surfer]
    - autogenstudio
